### ISSUE TITLE
Anticlustering as a partitioning method

### ISSUE THREAD

**Issue by jmgirard** [tidymodels/rsample#266]
## Feature

Anticlustering seems to be a promising new method for partitioning data into equivalent parts. I wonder if you would be open to having this method implemented into rsample as a means of determining how to create partitions?

The paper describing this method is here:
Papenberg, M., & Klau, G. W. (2021). Using anticlustering to partition data sets into equivalent parts. _Psychological Methods, 26_(2), 161–174. https://doi.org/10/ghgt9v

An R package implementing this is here:
https://cran.r-project.org/package=anticlust

**Comment by juliasilge** [comment]
This looks super interesting @jmgirard! This specialized method with some specific system requirements is likely not a great fit for rsample itself, but rsample is extensible and you or someone else interested in this method could create an rsample extension package that implements this method within the tidymodels/rsample framework. For an example of how to do this, take a look at [spatialsample](https://github.com/tidymodels/spatialsample/), which implements rsample methods for spatial resampling methods (well, just one right now).

If you or someone else is interested in creating this package, please reach out because I and other members of the tidymodels team would be so happy to do code review before an initial release and offer support during development. 🙌

**Comment by jmgirard** [comment]
That makes a lot of sense. I hadn't noticed the special dependencies. I will look into the extension possibility this summer.

**Comment by juliasilge** [comment]
Sounds great! Please let us know if/when you would like any input or code review. 👍
