### ISSUE TITLE
Is there a way to resample without copying main data ?

### ISSUE THREAD

**Issue by sametsoekel** [tidymodels/rsample#335]
While working high volumed data it's really hard to manage memory during cross-validation. I think only indices information can be kept in `vfold_cv` and other sampling functions then we can call our folds with their indices from the main data.

I checked older issues and documentation to find a feature like this but didn't find anything useful. Sorry if I miss out.

**Comment by DavisVaughan** [comment]
rsample already does this

**Comment by sametsoekel** [comment]
I think I am misunderstood, let me explain with an examlpe;

```
library(rsample)

iris2 <- iris

resampl <- vfold_cv(iris2,v = 10)

rm(iris2)
gc()

apply(resampl[,'splits'],2,function(x) testing(x[[1]]))
```

I still can reach a resample even if I removed the main data in my calling environment

@mikemahoney218 @DavisVaughan

**Comment by mikemahoney218** [comment]
So, R uses what's known as [copy-on-modify](https://adv-r.hadley.nz/names-values.html) semantics (that link is being a little wonky for me, it goes to Chapter 2 of Advanced R). That means that, when you assign a new variable to the same data as another, no copy is actually made until you modify the underlying data for one of the variables. That means that `iris` and `iris2` are actually pointing at the same address in RAM:

``` r
library(rsample)

iris2 <- iris

lobstr::obj_addr(iris)
#> [1] "0x556d081af068"
lobstr::obj_addr(iris2)
#> [1] "0x556d081af068"
identical(
  lobstr::obj_addr(iris),
  lobstr::obj_addr(iris2)
)
#> [1] TRUE
```

This also means that `iris2` takes up literally 0 space in your RAM:

```r
lobstr::obj_size(iris, iris2)
#> * 7,200 B
#> *     0 B
```

But it _also_ means that when you get rid of iris2, you just got rid of one pointer to the same address. The "data" in resampl is pointing to the same address in memory as the original iris data frame, and so takes up 0 additional space:

```r
resampl <- vfold_cv(iris2,v = 10)

lobstr::obj_sizes(iris, iris2, resampl)
#> *  7,200 B
#> *      0 B
#> * 15,592 B

rm(iris2)
gc()
#>           used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells  880759 47.1    1691121 90.4  1299391 69.4
#> Vcells 1555610 11.9    8388608 64.0  2636807 20.2

apply(resampl[,'splits'],2,function(x) testing(x[[1]]))
#> $splits
#>     Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#> 5            5.0         3.6          1.4         0.2     setosa
#> 41           5.0         3.5          1.3         0.3     setosa
#> 51           7.0         3.2          4.7         1.4 versicolor
#> 57           6.3         3.3          4.7         1.6 versicolor
#> 63           6.0         2.2          4.0         1.0 versicolor
#> 78           6.7         3.0          5.0         1.7 versicolor
#> 112          6.4         2.7          5.3         1.9  virginica
#> 118          7.7         3.8          6.7         2.2  virginica
#> 120          6.0         2.2          5.0         1.5  virginica
#> 121          6.9         3.2          5.7         2.3  virginica
#> 131          7.4         2.8          6.1         1.9  virginica
#> 134          6.3         2.8          5.1         1.5  virginica
#> 136          7.7         3.0          6.1         2.3  virginica
#> 141          6.7         3.1          5.6         2.4  virginica
#> 145          6.7         3.3          5.7         2.5  virginica

lobstr::obj_addr(iris)
#> [1] "0x556d081af068"
lobstr::obj_addr(resampl$splits[[1]]$data)
#> [1] "0x556d081af068"

identical(
  lobstr::obj_addr(iris),
  lobstr::obj_addr(resampl$splits[[1]]$data)
)
#> [1] TRUE
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Note that `gc()` here didn't get rid of anything we're paying attention to, because both `iris` and `resampl` still point at the same address.

If you modified `iris,` _then_ the two would no longer point at the same address space, but that's desirable -- the indices stored in `resampl` no longer correspond to `iris`.

``` r
library(rsample)
x <- data.frame(
  x = rnorm(50)
)
r <- vfold_cv(x)

lobstr::obj_addr(x)
#> [1] "0x55a6164259b8"
lobstr::obj_addr(r$splits[[1]]$data)
#> [1] "0x55a6164259b8"

x <- 2

lobstr::obj_addr(x)
#> [1] "0x55a614b217d0"
lobstr::obj_addr(r$splits[[1]]$data)
#> [1] "0x55a6164259b8"
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
