### ISSUE TITLE
`get_rsplit()` helper to extract split objects?

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/rsample#389]
## Feature

Hi all!

Right now, I _believe_ the best way for users to get individual rsplit objects from an rset is to index into the rset themselves:

``` r
library(rsample)

ex_vfold <- vfold_cv(Orange, v = 2)
ex_vfold$splits[[1]]
#> <Analysis/Assess/Total>
#> <17/18/35>
```

I'm wondering if it would be useful to provide a helper function, `get_rsplit()` or similar, to extract these? My personal interest is in making the spatialsample documentation a bit cleaner (because `autoplot()` has separate methods for rset and rsplit objects), but I think it might also be a friendlier interface overall:

```r
get_rsplit <- function(rset, n, ...) {
  UseMethod("get_rsplit")
}

get_rsplit.rset <- function(rset, n, ...) rset$splits[[n]]

get_rsplit.default <- function(rset, n, ...) {
  cls <- paste0("'", class(x), "'", collapse = ", ")
  rlang::abort(
    paste("No `get_rsplit()` method for this class(es)", cls)
  )
}

get_rsplit(ex_vfold, 1)
#> <Analysis/Assess/Total>
#> <17/18/35>
```

Thanks!

**Comment by hfrick** [comment]
I think this might not exist yet because `rsplit` objects (other than those from `initial_split()` and friends) are not generally meant to be used standalone. 

That said, I wouldn't mind such functionality for illustration purposes. Do you want to make a PR for that? 

If so, could you please

- call the arg `index` instead of `n` 
- add a dot prefix to the name since it's more developer-focussed, so `.get_rsplit()`
- add `@keyword internal`
