### ISSUE TITLE
Format function signatures for pkgdown

### ISSUE THREAD

**Issue by hfrick** [tidymodels/rsample#476]
It'd be nice to not have to scroll horizontally in situations like this:

<img width="836" alt="Screenshot 2024-05-16 at 10 37 49" src="https://github.com/tidymodels/rsample/assets/12950918/067a8652-23cf-441a-9618-052930a6b270">

**Comment by jplecavalier** [comment]
This behaviour is actually caused by `roxygen2:::wrap_usage()` default behaviour of wrapping the `@usage` bloc on multiple lines only when the width is greater than 80 characters. As one could see, this specific example is 79 characters wide and this explains why it is not wrapped automatically.

 ```
nchar("mc_cv(data, prop = 3/4, times = 25, strata = NULL, breaks = 4, pool = 0.1, ...)")
#>  [1] 79
```

A workaround to solve this specific problem would be to manually write the `@usage` bloc in the function header, but as discussed with @hfrick at tidy-dev-day, this is not a good idea.

**Comment by hfrick** [comment]
Thank you for looking into this @jplecavalier ! I'll close this this is more complexity than is worth it here
