### ISSUE TITLE
vfold_cv(repeats > 1) should return a `repeated_vfold_cv` class object

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/rsample#82]
Because the column structure changes of the returned tibble, and there are two columns for `id`, it would be nice if the class was different. This will be useful when tuning over a repeated cv object so we make sure and extract both `id` and `id2`.

**Comment by juliasilge** [comment]
I was working on a PR to implement this (add a class) but @DavisVaughan suggested something during review that made me wonder if we should take a different approach.

When we tune over repeated CV, we do not do any nesting or treating the resamples in a special way, right? We want to treat these resamples as independent and all the same as each other and aggregate over all of them, not considering which ones come from which repeats? Is that right?

If that is right, then why don't we keep the class as is (no special class for repeated CV), keep the attributes as is (so that we can get out `repeats` when needed), and combine the repeats and IDs into one `id` column, to look like below:

``` r
library(rsample)

result <- vfold_cv(mtcars, v = 10, repeats = 2)
result
#> #  10-fold cross-validation repeated 2 times 
#> # A tibble: 20 × 3
#>    splits         id      id2   
#>    <list>         <chr>   <chr> 
#>  1 <split [28/4]> Repeat1 Fold01
#>  2 <split [28/4]> Repeat1 Fold02
#>  3 <split [29/3]> Repeat1 Fold03
#>  4 <split [29/3]> Repeat1 Fold04
#>  5 <split [29/3]> Repeat1 Fold05
#>  6 <split [29/3]> Repeat1 Fold06
#>  7 <split [29/3]> Repeat1 Fold07
#>  8 <split [29/3]> Repeat1 Fold08
#>  9 <split [29/3]> Repeat1 Fold09
#> 10 <split [29/3]> Repeat1 Fold10
#> 11 <split [28/4]> Repeat2 Fold01
#> 12 <split [28/4]> Repeat2 Fold02
#> 13 <split [29/3]> Repeat2 Fold03
#> 14 <split [29/3]> Repeat2 Fold04
#> 15 <split [29/3]> Repeat2 Fold05
#> 16 <split [29/3]> Repeat2 Fold06
#> 17 <split [29/3]> Repeat2 Fold07
#> 18 <split [29/3]> Repeat2 Fold08
#> 19 <split [29/3]> Repeat2 Fold09
#> 20 <split [29/3]> Repeat2 Fold10
tidyr::unite(result, col = "id", id, id2, sep = "_")
#> # A tibble: 20 × 2
#>    splits         id            
#>    <list>         <chr>         
#>  1 <split [28/4]> Repeat1_Fold01
#>  2 <split [28/4]> Repeat1_Fold02
#>  3 <split [29/3]> Repeat1_Fold03
#>  4 <split [29/3]> Repeat1_Fold04
#>  5 <split [29/3]> Repeat1_Fold05
#>  6 <split [29/3]> Repeat1_Fold06
#>  7 <split [29/3]> Repeat1_Fold07
#>  8 <split [29/3]> Repeat1_Fold08
#>  9 <split [29/3]> Repeat1_Fold09
#> 10 <split [29/3]> Repeat1_Fold10
#> 11 <split [28/4]> Repeat2_Fold01
#> 12 <split [28/4]> Repeat2_Fold02
#> 13 <split [29/3]> Repeat2_Fold03
#> 14 <split [29/3]> Repeat2_Fold04
#> 15 <split [29/3]> Repeat2_Fold05
#> 16 <split [29/3]> Repeat2_Fold06
#> 17 <split [29/3]> Repeat2_Fold07
#> 18 <split [29/3]> Repeat2_Fold08
#> 19 <split [29/3]> Repeat2_Fold09
#> 20 <split [29/3]> Repeat2_Fold10
```

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Do the two columns help us in tune somehow? The two columns could be parsed out via `tidyr::separate()` for anyone who needs it for custom work. Thoughts @DavisVaughan and @topepo?

**Comment by DavisVaughan** [comment]
I think that would work. I think that even `repeats = 1` should get `Repeat1_Fold<j>` for consistency and ease of implementation.

**Comment by juliasilge** [comment]
I chatted with Max and it turns out we do currently use that `id2` column in a few places such as tidyposterior. So upon reflection:

- we can get the `repeats` out of the attributes when needed
- the function is currently type stable
- both tune and packages like tidyposterior work with the dataframe structure output

I'm going to say let's **not** change anything after all but instead close this issue; let's make no changes to the `id` column structure and no changes to the classes.
