### ISSUE TITLE
Use rsample for creating many (possibly overlapping) subsets?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidymodels/rsample#92]
I am doing a lot of subset analysis, where I estimate the same model on the whole data, then separately on male/female, then on young/old, etc. For now, I pretty much do `rbind(full, nest(full, -gender), nest(full, age)` etc, which results in very large datasets. 

I am wondering whether rsample could be used/forked for such a use? In essence, a subset of data is just a deterministic bootstrap, of size n < N. I feel rsample has a great way to deal efficiently with data memory, and that could be useful for other contexts such as subset analysis. Do you have any thoughts on this, and any hints on how one would proceed?

Thanks!!

**Comment by topepo** [comment]
Good question...

One thing that `rsample` exploits is that copies of _unmodified_ data are not new copies in memory. So if an `rset` object has 1000 rows, and the original data are in each element of the `split` column, there is no increase in memory. 

If you nest or subset the data when making a new data structure, you end up making copies. Instead of an `rsample` approach, you'd be better off doing an expansion of the data (as-is) along with some method of filtering. 

I don't know what that looks like but the general idea would be to iterate over the subgroups and do the analyses on the subsets (as opposed to creating a bunch of subsets then doing the analyses).
